import React from 'react'
import { db } from '@/lib/db/store'
import { generateQrCodeSvg } from '@/lib/mobile/qr'

interface DownloadPageProps {
  params: Promise<{ token: string }>
}

export default async function DownloadPage({ params }: DownloadPageProps) {
  const { token } = await params
  const link = await db.getShareableLinkByToken(token)

  if (!link) {
    return (
      <main style={styles.container}>
        <div style={styles.card}>
          <div style={styles.errorIcon}>⚠️</div>
          <h1 style={styles.title}>Download Link Unavailable</h1>
          <p style={styles.description}>
            This APK download link is invalid, expired, or has been revoked by the project owner.
          </p>
        </div>
      </main>
    )
  }

  const artifact = await db.getProjectArtifact(link.artifact_id)
  if (!artifact || artifact.status !== 'available') {
    return (
      <main style={styles.container}>
        <div style={styles.card}>
          <div style={styles.errorIcon}>📦</div>
          <h1 style={styles.title}>Artifact Not Found</h1>
          <p style={styles.description}>
            The requested Android APK file is no longer available.
          </p>
        </div>
      </main>
    )
  }

  const project = await db.findProjectById(artifact.project_id)
  const appName = project?.name || 'Mobile App'
  const sizeMb = (artifact.size_bytes / (1024 * 1024)).toFixed(2)
  const downloadApiUrl = `/api/mobile/download/${token}`
  const qrSvg = generateQrCodeSvg(`https://vx.dev/download/${token}`, 180)

  return (
    <main style={styles.container}>
      <div style={styles.card}>
        <div style={styles.header}>
          <div style={styles.appIconWrap}>
            <span style={{ fontSize: '32px' }}>📱</span>
          </div>
          <div>
            <h1 style={styles.title}>{appName}</h1>
            <div style={styles.badgeRow}>
              <span style={styles.badge}>Android APK</span>
              <span style={styles.badge}>v{artifact.version} (Build {artifact.version_code})</span>
            </div>
          </div>
        </div>

        <div style={styles.downloadBox}>
          <a href={downloadApiUrl} style={styles.downloadButton} download={artifact.file_name}>
            <span>Download APK</span>
            <span style={styles.sizeTag}>{sizeMb} MB</span>
          </a>
        </div>

        <div style={styles.detailsGrid}>
          <div style={styles.detailItem}>
            <span style={styles.detailLabel}>File Name</span>
            <span style={styles.detailValue}>{artifact.file_name}</span>
          </div>
          <div style={styles.detailItem}>
            <span style={styles.detailLabel}>File Size</span>
            <span style={styles.detailValue}>{sizeMb} MB ({artifact.size_bytes.toLocaleString()} bytes)</span>
          </div>
          <div style={styles.detailItem}>
            <span style={styles.detailLabel}>SHA-256 Digest</span>
            <span style={{ ...styles.detailValue, fontFamily: 'monospace', fontSize: '11px', wordBreak: 'break-all' }}>
              {artifact.checksum}
            </span>
          </div>
          <div style={styles.detailItem}>
            <span style={styles.detailLabel}>Total Downloads</span>
            <span style={styles.detailValue}>{link.download_count}</span>
          </div>
        </div>

        <div style={styles.qrSection}>
          <div style={styles.qrTitle}>Scan QR Code on Android Device</div>
          <div
            style={styles.qrContainer}
            dangerouslySetInnerHTML={{ __html: qrSvg }}
          />
        </div>

        <div style={styles.instructions}>
          <h3 style={styles.instrTitle}>Installation Instructions</h3>
          <ol style={styles.instrList}>
            <li>Tap <strong>Download APK</strong> above to download file.</li>
            <li>When download completes, open the notification or file manager.</li>
            <li>Tap <strong>Install</strong>. If prompted by Android, enable &quot;Allow installation from unknown sources&quot; for your browser.</li>
          </ol>
        </div>

        <div style={styles.footer}>
          Verified clean Android APK generated by VX Mobile App Builder
        </div>
      </div>
    </main>
  )
}

const styles: Record<string, React.CSSProperties> = {
  container: {
    minHeight: '100vh',
    backgroundColor: '#0d0d11',
    color: '#ededed',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '24px 16px',
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
  },
  card: {
    backgroundColor: '#18181c',
    border: '1px solid #27272a',
    borderRadius: '16px',
    padding: '32px 24px',
    maxWidth: '460px',
    width: '100%',
    boxShadow: '0 12px 32px rgba(0, 0, 0, 0.6)',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
    marginBottom: '24px',
  },
  appIconWrap: {
    width: '64px',
    height: '64px',
    backgroundColor: '#27272a',
    borderRadius: '16px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    border: '1px solid #3f3f46',
  },
  title: {
    fontSize: '22px',
    fontWeight: 'bold',
    color: '#ffffff',
    margin: '0 0 6px 0',
  },
  badgeRow: {
    display: 'flex',
    gap: '8px',
    flexWrap: 'wrap',
  },
  badge: {
    backgroundColor: '#27272a',
    color: '#a1a1aa',
    fontSize: '11px',
    padding: '2px 8px',
    borderRadius: '6px',
    fontWeight: '500',
  },
  downloadBox: {
    marginBottom: '24px',
  },
  downloadButton: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#22c55e',
    color: '#000000',
    padding: '14px 20px',
    borderRadius: '12px',
    fontWeight: 'bold',
    fontSize: '16px',
    textDecoration: 'none',
    boxShadow: '0 4px 14px rgba(34, 197, 94, 0.3)',
    transition: 'transform 0.15s ease',
  },
  sizeTag: {
    backgroundColor: 'rgba(0, 0, 0, 0.15)',
    padding: '4px 10px',
    borderRadius: '8px',
    fontSize: '12px',
  },
  detailsGrid: {
    display: 'grid',
    gap: '12px',
    backgroundColor: '#121215',
    padding: '16px',
    borderRadius: '12px',
    border: '1px solid #27272a',
    marginBottom: '24px',
  },
  detailItem: {
    display: 'flex',
    flexDirection: 'column',
    gap: '2px',
  },
  detailLabel: {
    fontSize: '11px',
    color: '#71717a',
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
  },
  detailValue: {
    fontSize: '13px',
    color: '#e4e4e7',
    fontWeight: '500',
  },
  qrSection: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    marginBottom: '24px',
    padding: '16px',
    backgroundColor: '#121215',
    borderRadius: '12px',
    border: '1px solid #27272a',
  },
  qrTitle: {
    fontSize: '12px',
    color: '#a1a1aa',
    marginBottom: '12px',
    fontWeight: '500',
  },
  qrContainer: {
    padding: '8px',
    backgroundColor: '#18181c',
    borderRadius: '12px',
    border: '1px solid #27272a',
  },
  instructions: {
    backgroundColor: '#121215',
    padding: '16px',
    borderRadius: '12px',
    border: '1px solid #27272a',
    marginBottom: '20px',
  },
  instrTitle: {
    fontSize: '13px',
    color: '#f4f4f5',
    margin: '0 0 8px 0',
  },
  instrList: {
    margin: 0,
    paddingLeft: '20px',
    fontSize: '12px',
    color: '#a1a1aa',
    lineHeight: '1.6',
  },
  footer: {
    textAlign: 'center',
    fontSize: '11px',
    color: '#52525b',
  },
  description: {
    fontSize: '14px',
    color: '#a1a1aa',
    lineHeight: '1.5',
    marginTop: '12px',
  },
  errorIcon: {
    fontSize: '40px',
    marginBottom: '12px',
  },
}
